on: push
name: Build and Deploy Mitools app on server
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
      
    - name: 'Create env file'
      run: |
        echo "${{ vars.ENV_FILE }}" > .env

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'
      
    - name: Build Project
      run: |
        npm install
        npm run build
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 128.140.113.155
        username: github_action_deploy
        password: ${{ secrets.FTP_PASSWORD }}
